_target_: src.models.hsl_gnn.GNNModel

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

gnn:
  _target_: src.models.components.simple_gnn_model.GNNModel
  num_features: 12
  hidden_dim: 16
  num_classes: 7

# compile model for faster training with pytorch 2.0
compile: false
